### ISSUE TITLE
stretch feature front-end

### ISSUE THREAD

**Issue by pgrapes** [andrew-worsfold/tailor-advanced#1]
Hi. Tried this with WP default theme.  The stretch feature works in admin canvas.  However, the front end it isn't working for me. No js applied.

**Comment by andrew-worsfold** [comment]
@pgrapes -

This should be working now under the latest commit.  Can you please try editing and saving a section using this latest version results in the JavaScript being applied correctly in the frontend?

Many thanks,
Andrew.

**Comment by pgrapes** [comment]
Hey Andrew. Yes, it's working correctly now.
